### ISSUE TITLE
各国固有のメタ構文変数追加

### ISSUE THREAD

**Issue by ezaki** [officel/spelling-dictionary#17]
from #16 

[RFC 3092](https://www.ietf.org/rfc/rfc3092.txt)に掲載されていないメタ構文変数( `hoge` 等)を
辞書へ登録するべきでしょうか。

メタ構文変数は通例として、コードの利用者が「ありえない単語」として認識できるものを利用されるかと思います。
例えば日本では `hoge` , `fuga` などの文字列が使われることが見られ、
これらについては typo として扱われるべきでは無いため、辞書に登録することが妥当かと考えています。

ご意見お願いします。 :pray::pray:

**Comment by officel** [comment]
ありがとうございます！

メタ構文文字列として、正しい（？）というか、rfc的には英文に記されてるものが正だと思うよ、
そちらを利用するほうがいいんじゃないかな、を伝えることができると、
日本文化的（？）な hoge や fuga は含まないほうがいいのかな、とちょっと考えたりしていました。

が、

rfcへのリンクを明示した上で（済み）、
rfcに示されてるジャーゴンを全て含みつつ  (bar, baz, qux, quux, corge, grault, garply, waldo, fred, plugh, xyzzy, thud)、
日本文化圏では hoge, fuga 等を利用する例が多いため追加している、
とREADME.mdで説明書きを加えていただけたら全部ありでいいのではないか、と今考えています。

本来正っぽいのはこれ（rfc）、現状現時点ではこう(hoge,fuga)、なのでこうすることにしたよ(README)、というのが伝えられればいいのかな、という感じです。

どうでしょうか？

**Comment by ezaki** [comment]
理解しました。
ご提案された内容のようにするのが良さそうですね　👍 
そのように更新しておきました。

現時点で `foo` `bar` など公式に登録されているらしい単語も含まれますが、
それは許容でOKですか？

**Comment by officel** [comment]
公式対応のやつも入ってていいと思います！
他の辞書にも入っているので。。。
（IntelliJ とか TYPO じゃなくなったんですよ。 webstorm は相変わらず TYPO ですが。。。）

**Comment by ezaki** [comment]
了解です！
IntelliJ でしか見てなかったので webstorm とかで入ってないってのは知りませんでしたョ 😶

**Comment by officel** [comment]
:smile: 
こっちは取り込み済みなので締めますね

https://github.com/officel/spelling-dictionary/commit/c3e88c0e46c1593f36e522f6ac6c41b925eca288

**Comment by officel** [comment]
目視が甘くてすいません。。。
カンマが一個残っていたので除去して all.dic 作成と一緒に master に送りました。

**Comment by ezaki** [comment]
失礼しました 🙇 
修正ありがとうございます。
