### ISSUE TITLE
want to change dictionary data format

### ISSUE THREAD

**Issue by ezaki** [officel/spelling-dictionary#18]
現時点での管理は

- *.dic file
- README.md

を各ディレクトリ下に配置しているが、編集の度に二箇所変更しなければならないため
手間がかかり、誤入力の可能性が発生する。

json または yaml などの表記でデータを作り、
CI で.dicファイルを自動生成できるようにしたい。
（コメントを使いたいので yaml の方が適しているかと思います）

その他のデータフォーマットも含め、検討させてください。 😺

**Comment by officel** [comment]
あ、リポジトリ下の bin に mk_dic.php ってファイルがあって、単純に php bin/mk_dic.php ってすると、
dictionaries/(.*$)/README.md を読み込み、$1.dic と all/all.dic が出力されるので、
（phpがあれば）試してみてください。

元データ部分を何で作ろうか、CI的に言語は何で回そうか、は確かに今後の検討課題かなとは思います。
個人的には yaml 化に一票ですー

**Comment by ezaki** [comment]
了解です！
データ本体にコメントなどもかけるようになると

root
|-- dictionaries
    |
    |--(各辞書ディレクトリ)
        |--*.dic file
        |--README.md

から

root
|-- dictionaries
    |--*.yml file

みたいな、ディレクトリ階層が一つ下がって見やすいかなと思ったんですよね。
各ディレクトリに readme があるより、github page に情報を出すようにして
そちらを参照してもらう方がわかりやすいような気もしますし。

回す言語は正直変換できれば何でもいい感じですが、
python  とか Go とかだとそれっぽいですかね。
php だと何となくWebページ生成しそうなイメージなので。

**Comment by officel** [comment]
IntelliJ だとディレクトリ単位で辞書が食われるので、 dictionaries 下でフォルダを分けてあげないと、個別に設定できないんです。。。
（そのために全部用 all が上位にある）
dictionaries 以下に *.dic ってしちゃうと個別にならないので、個別に処理したい時に邪魔かなぁと。
各フォルダに README.md があると、github 上でフォルダを開いた時にそれぞれ表示されるので便利かなって。。。

**Comment by ezaki** [comment]
なるほど、ディレクトリ単位になってることを失念していました。。。

では、

```
root
├ dictionaries
│ ├ all
│ │ └ all.dic
│ ├ foo
│ │ └ foo.dic
│ ├ bar
│ │ └ bar.dic
│ └ foobar
│      └ foobar.dic
└ src
     ├ foo.yml
     ├ bar.yml
     └ foobar.yml
```

こんな感じで、出力用ディレクトリをdictionariesにして、データを別ディレクトリ(srcなど)に分割するのはどうでしょうか。
やっぱり個別にreadmeを書くとなると、yaml と readme の両方を編集する必要が発生してしまうので。

**Comment by officel** [comment]
でいくと、構成的には今のままで、 yaml(またはjson)形式のファイルを入力として、各ディレクトリに .dic と README.md を出力する、感じではどうでしょうか？

```
root
├ all
│ └ all.dic    # このファイルは各ディレクトリから自動
│ └ README.md  # このファイルは手動
├ bin
├ dictionaries
│ ├ foo
│ │ └ foo.dic   # 自動生成
│ │ └ README.md # 自動生成
│ │ └ foo.yaml  # 入力ファイル。いじるのは.yamlだけ
│ ├ bar
│ │ └ bar.dic
│ │ └ README.md
│ │ └ bar.yaml
│ └ foobar
│      └ foobar.dic
│      └ README.md
│      └ foobar.yaml

```

作業中も対象のフォルダだけ見れば済みますし、入力は YAML に一本化すればWebベースで見た時にフォローできますし。
github pages にも出すなら docs フォルダを作って、そっちにも .html で出力する感じですね。
それだと sphinx 使ったほうが手っ取り早くなるかもしれないですね。。。ｗ

**Comment by ezaki** [comment]
議論してて気づきましたが、私はコードとドキュメント(*.ymlファイルとreadmeファイル)が混ざってるのがどうにも気になるので、さっきのような構成にしたくなるようです。
このあたりは考え方の違いもあるので、先ほどのご提案のようにとりあえずyamlだけ、いじればOKになるように・・・。

と、言いたいもののやっぱり気になるので確認させてもらうのですが、
readmeを自動生成にするっていうことは（私が言い始めたのですが）、辞書に入れてる語句、入れない語句の判別などのコメントもやっぱりyamlにしていくんですよね。

ということは、yamlの内容は

```
see: example.com
description: foobar
 words:
  - foo
  - bar
```

みたいな感じになりますよね。

やっぱり　(webで参照できるようにしてもらえるなら特に)各ディレクトリにreadme入れなくていいように感じるのですが、どうなんでしょうか。

（こういう思想的な話になると、もう一人くらい議論できる方が欲しいですね。）

**Comment by officel** [comment]
yamlの中はそんな感じになると思います。
あと、srcとdistを分けるのは確かにそのほうがいいと思ってもいます。
（JSのトランスパイラとかSassとかもそうですしね）

ただ、README.md が置いてあると、便利には違いないのと、本質的には更新の仕掛けではなく生成される .dic （とall.dic）が大事って考えると、情報は一塊になってるほうがわかりやすくないかなぁと。。。

こんな風に README.md あるとcloneはしないけど中身だけ眺める、みたいな時に便利です。。。
https://github.com/LibreOffice/dictionaries/tree/master/en


議論についても本当にそうですね。
まだ始めたばかりですし、ないものねだりはできませんが、もうひとりふたりくらいいてくれると議論が尽くせそうでいいなぁと思います。
（実際はどうあれ表面的には）民主主義的な解決方法が取れると思いますしｗ

ということは一旦棚上げして、他の人の参加を待つ、のがいいかもしれないなと思いました。

**Comment by ezaki** [comment]
なるほど、参考URLありがとうございます。

cloneしたときにreadmeをそれぞれ作るとファイル数が2倍近く増えるのと、
編集してくれる人がどれを編集するべきか、極力迷わないように（readmeも自分で書くのか、ということで）する方が、ということでない方がいいのではないかと思っていましたが、色々な考え方があるのですね。

確かに、他の方に来てもらえてから考えるのもアリですね。
では、とりあえず、yamlに統一することは合意できているので、先にyamlのフォーマット（書くべき内容・形式）を
決めてしまうのはどうでしょうか。

よろしければ yaml の件について、 issue 立ててもらえるとありがたいです。 🙏

**Comment by officel** [comment]
容量は確かに気になるかもと思っています。
普段業務では大容量リポジトリばっかり弄っているので、言うてたいしたことないやろ、とも思っていますがｗ

yamlのフォーマットを決める issue 立てました！
https://github.com/officel/spelling-dictionary/issues/20
