### ISSUE TITLE
add words information in readme.md

### ISSUE THREAD

**Issue by ezaki** [officel/spelling-dictionary#24]
現在のところ README.md 中の word 項目がリストになっていますが、
word ごとの description などが入れにくい感じになっていますね。

```
## List

### EC2
#### Original Name
Amazon EC2
#### Description
Virtual Servers in the Cloud
#### See
https://aws.amazon.com/ec2/
```

#### Original Name
Amazon EC2
#### Description
Virtual Servers in the Cloud
#### See
https://aws.amazon.com/ec2/

こんな構造にするのはどうでしょうか。

**Comment by officel** [comment]
これはこれでもいいと思うのですが、h要素にしたタイトル部に意味があるわけではないのと、長くなっちゃうので、いっそのこと

```
## List

* EC2
  * Amazon EC2  https://aws.amazon.com/ec2/
  * Virtual Servers in the Cloud
```

## List

* EC2
  * Amazon EC2  https://aws.amazon.com/ec2/
  * Virtual Servers in the Cloud

このくらいコンパクトにしてもいいんじゃないかなと思ったり思わなかったりします。。。
正直他のも組んでみたら他にも書きたいこととか出るかもなので、今のところは仮置きでいいと思っています。

**Comment by ezaki** [comment]
OKです。
ではそんな感じでいきましょう。
