### ISSUE TITLE
add service name

### ISSUE THREAD

**Issue by ezaki** [officel/spelling-dictionary#25]
nginx や mysql, mariadb のような、サービス系（といえばいいのかどうかわからないですが）の
名前の辞書は分類としてはどんな感じで登録できますか？

**Comment by officel** [comment]
今のところ dictionaries ディレクトリ内にそれぞれのサービス名またはアプリケーション名で登録するのがわかりやすいと思っています。
うまくコトが進んで dictionaries 内がすごくたくさんになったら再整理する、という方針にしたいと考えています。

**Comment by ezaki** [comment]
ということは、

```
dictionaries
├ nginx
│ └ nginx.yaml
└ mariadb
     └ mariadb.yaml
```

こんな感じですね。
