### ISSUE TITLE
how to fix py2 or py3 with windows. about CRLF...

### ISSUE THREAD

**Issue by officel** [officel/spelling-dictionary#27]
英語が適当でアレなんですけれども。。。
python のバージョンが２系と３系で困ったちゃんとか、Windows機だと dic と md の改行コードが CRLF になっちゃうという問題があるみたいです。
Linux マシンの2系は平気みたい。。。？

**Comment by ezaki** [comment]
windows で触ってないので考えてませんでした。。。
ちょっと調べてみます。

**Comment by officel** [comment]
こんにちわ。
python力不足でちゃんと説明できなくてすいません。。。

今のところ確認できてる問題は
* 3系構文（printがfunctionになったので丸括弧で囲まないとダメなやつ。反映済み）他は平気みたい
* 2系と3系の改行の扱い（open構文での newline の扱い方の違い）
  * ↑これが原因で Windows では LF のファイルを読み込んでも出力時にCRLFにしてしまう
  * 2系でも3系でも動くようにするにはバージョンで書き分けないとダメかも

という感じです。
更新後のファイルをLFにするなどを忘れなければまぁ問題ないので、そんなに重要ってわけではないと思っているので、簡単に思いつく範囲でどうにかできればよし、そうじゃなければこういう課題があるというのを注意すればいいかなと思っています。

**Comment by ezaki** [comment]
#28 改行の問題はこんな感じですかね？

もともとVer.2 の python  で書いてたのは、ファイル出力は将来的には
CIで自動生成になるのかなという思いから、linuxでよく使用されている方の Ver2 を
選びたかったという背景があります。

バージョンやらなんやらで混乱するようなら、別にpythonにこだわる必要もないので
他の言語にしちゃってもいいんですがねー 😶

**Comment by officel** [comment]
他の言語にしても似たような問題にはきっとぶつかりますね。たぶん。。。
Ruby だって1.9系と2系ではぎゃああああってなりがちですし。。。
（その点PHPは枯れてて優秀ｗ PHP7でも同じように動きますしｗ）

CIはCIでどれかの言語、バージョンにあわせて固定でいいかなと思っています。
CIに送る前のローカル作業的なところで作業する人ごとの環境で差異が出るのはちょっとどうかな、くらいです。
それこそ今二人しかいないじゃんって言ったらそこまでなんですけどｗ

**Comment by ezaki** [comment]
本来は新しい方を使えばいいんですけどね。
OSに初期装備されているのが Ver2 の場合が多いので、そっちで書いたってだけなんですよね。

なんかややこしいですし、Ruby とか PHP とかで書きますか？
python で書くとしたら、2も3も動くようにするのは難しいので、どちらかに揃える感じになりますね。

**Comment by officel** [comment]
わかります。pythonだとそんな感じですよね。
とりあえずここはそんなにがんばるところじゃないんですが、もしよかったら３系にしちゃいませんか？
バイナリにして出力ではなくて、open に newline で "\n" 渡せばいいはずなので。。。
TravisCI にしても CircleCI にしても3系いけますんで。。。

**Comment by officel** [comment]
ありがとうございます！
もろもろmasterにマージしました。
