### ISSUE TITLE
web service

### ISSUE THREAD

**Issue by officel** [officel/spelling-dictionary#34]
インターネットサービスの名称を入れる

**Comment by ezaki** [comment]
クラウドサービスであれば、私が使うことがあるのは

- [x]  Heroku (https://www.heroku.com)
- [x]  Wercker (http://www.wercker.com)
- [x]  ConoHa (https://www.conoha.jp/conoha/)
- [ ]  slack (https://slack.com)
- [ ]  cloud9 (https://c9.io)

この辺ですかね。

**Comment by officel** [comment]
Heroku, Wercker, ConoHa は IntelliJ 上でTYPOになるようなので入れました。
slack と cloud9 は文字的に TYPO にならないですかね？

**Comment by ezaki** [comment]
ありがとうございます。
とりあえず確認せずに放り込んでるんで、typo扱いにならなかったら弾いてください・・・ 😶

**Comment by officel** [comment]
了解です。
言語ファイルとか設定によっては妙なところで TYPO になったりならなかったりもするので、なにか見つけたら教えてください。

**Comment by officel** [comment]
一旦マージしますた。
