### ISSUE TITLE
add JavaScript event handlers name 

### ISSUE THREAD

**Issue by ezaki** [officel/spelling-dictionary#40]
whatwg の eventページに 掲載されている([https://html.spec.whatwg.org/multipage/webappapis.html#events](https://html.spec.whatwg.org/multipage/webappapis.html#events))
イベントについて、typo扱いになるものが多い(特にmousedownなどの二語続いているもの)ので
これらを収録してもらいたい 😺

**Comment by officel** [comment]
@keika299 やってみましたん。一旦イベントハンドラだけ全部入れてみました。
whatwg にあるイベントハンドラはJS用とは限らない（という立て付けになっている）ので、フォルダはhtmlにしてみました。そもそも参照先ページもhtmlのスペックページだし。

**Comment by ezaki** [comment]
@officel ありがとうございます。
on がついてない、addEventListener で使用するパターンの方は入れられますか？

**Comment by officel** [comment]
@keika299 こんな感じですかね。確かに大部分がtypoでした。厳密にはチェックしてないですけど、一般的な英単語として認識されるやつでtypoになってないものは削ってみました。（まだ少し残ってるけどまぁいいかなみたいな）

**Comment by ezaki** [comment]
@officel ありがとうございます!
それでお願いします。

**Comment by officel** [comment]
@keika299 
#41 マージしました！
